server:
  port: 5000
logging:
  level:
    root: info
    
spring:
  application:
    name: app
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
       cache:
         use_query_cache: true  

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
  endpoint:
    health:
      enabled: true

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/books
    username: user
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
       cache:
         use_query_cache: true  

---

spring:
  profiles: aws
  datasource:
    url: jdbc:mysql://database-3.ct5de698vppf.eu-central-1.rds.amazonaws.com:3306/books
    username: rds-iam-user
    type: nl.leomoot.app.jdbc.RdsIamHikariAuthDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
       cache:
         use_query_cache: true      
